version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "09:30"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 99
    reviewers:
      - khanhnt2
    groups:
      tungstenite:
        patterns:
          - "hyper-tungstenite"
          - "tokio-tungstenite"
      rustls:
        patterns:
          - "tokio-rustls"
          - "hyper-rustls"
      native-tls:
        patterns:
          - "tokio-native-tls"
          - "hyper-tls"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "09:30"
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 10
    reviewers:
      - khanhnt2
